low = ["traitor", "changeling", "obsessed", "paradox_clone", "cortical_borer"]
medium = ["heretic", "abductor", "nightmare", "bloodsucker", "cortical_borer/hivemind"]
high = ["cult", "rev/head", "wizard", "clock_cultist", "ninja"]
